name: Build PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix build
        run: nix build

      - name: Deploy pdf
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pdf
          publish_dir: ./result
          force_orphan: true
