name: Build PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: nix build
        run: nix --print-build-logs build -o result

      - name: Copy results
        run: |
          mkdir public
          cp -L --no-preserve=all -t public ./result/*

      - name: Deploy pdf
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pdf
          publish_dir: ./public
          force_orphan: true
